### ISSUE TITLE
install

### ISSUE THREAD

**Issue by foXaCe** [lbschenkel/broadlink-bridge#1]
hello, 
the addon does not install for me
odroid xu4 card

**Comment by lbschenkel** [comment]
Hi, this should have been reported against:
https://github.com/lbschenkel/hass-addon-broadlink-bridge

I believe this was because I only declared the base image for `x86-64` architecture, not `arm`.
I have fixed this on https://github.com/lbschenkel/hass-addon-broadlink-bridge/commit/18d6516026a8949d3244d6704f2df90103e70250.
Please go to the "Add-on Store" tab in the "Hass.io" panel, press the "Reload" button on the top right corner, and try installing the add-on again.

In case it still doesn't work, please file a bug against that repo and include any error messages showing in the "System" tab (without logs I can't really know what went wrong).
